defmodule MakeupSqlTest do
  use ExUnit.Case
  doctest MakeupSql

  test "it works" do
    query = """
    WITH computed_dates AS (
       SELECT dates::date AS date
         FROM generate_series(
                current_date - $1::interval,
                current_date - interval '1 day',
                interval '1 day'
              ) AS dates
     -- comment
     )
      SELECT dates.date AS day, count(clicks.id) AS count
        FROM computed_dates AS dates
             LEFT JOIN clicks AS clicks ON date(clicks.inserted_at) = dates.date
       WHERE clicks.link_id = $2
    GROUP BY dates.date
    ORDER BY dates.date;
    """

    tokens = MakeupSql.lex(query)

    assert is_list(tokens)

    assert tokens == [
      {:keyword_reserved, %{language: :sql}, "WITH"},
      {:whitespace, %{language: :sql}, " "},
      {:name, %{language: :sql}, ~c"computed_dates"},
      {:whitespace, %{language: :sql}, " "},
      {:keyword_reserved, %{language: :sql}, "AS"},
      {:whitespace, %{language: :sql}, " "},
      {:punctuation, %{language: :sql}, 40},
      {:whitespace, %{language: :sql}, "\n   "},
      {:keyword_reserved, %{language: :sql}, "SELECT"},
      {:whitespace, %{language: :sql}, " "},
      {:name, %{language: :sql}, ~c"dates"},
      {:punctuation, %{language: :sql}, 58},
      {:punctuation, %{language: :sql}, 58},
      {:keyword_reserved, %{language: :sql}, "date"},
      {:whitespace, %{language: :sql}, " "},
      {:keyword_reserved, %{language: :sql}, "AS"},
      {:whitespace, %{language: :sql}, " "},
      {:keyword_reserved, %{language: :sql}, "date"},
      {:whitespace, %{language: :sql}, "\n     "},
      {:keyword_reserved, %{language: :sql}, "FROM"},
      {:whitespace, %{language: :sql}, " "},
      {:name, %{language: :sql}, ~c"generate_series"},
      {:punctuation, %{language: :sql}, 40},
      {:whitespace, %{language: :sql}, "\n            "},
      {:keyword_reserved, %{language: :sql}, "current_date"},
      {:whitespace, %{language: :sql}, " "},
      {:operator, %{language: :sql}, 45},
      {:whitespace, %{language: :sql}, " "},
      {:name, %{language: :sql}, "$1"},
      {:punctuation, %{language: :sql}, 58},
      {:punctuation, %{language: :sql}, 58},
      {:keyword_reserved, %{language: :sql}, "interval"},
      {:punctuation, %{language: :sql}, 44},
      {:whitespace, %{language: :sql}, "\n            "},
      {:keyword_reserved, %{language: :sql}, "current_date"},
      {:whitespace, %{language: :sql}, " "},
      {:operator, %{language: :sql}, 45},
      {:whitespace, %{language: :sql}, " "},
      {:keyword_reserved, %{language: :sql}, "interval"},
      {:whitespace, %{language: :sql}, " "},
      {:string_single, %{language: :sql}, ["'", 49, 32, 100, 97, 121, "'"]},
      {:punctuation, %{language: :sql}, 44},
      {:whitespace, %{language: :sql}, "\n            "},
      {:keyword_reserved, %{language: :sql}, "interval"},
      {:whitespace, %{language: :sql}, " "},
      {:string_single, %{language: :sql}, ["'", 49, 32, 100, 97, 121, "'"]},
      {:whitespace, %{language: :sql}, "\n          "},
      {:punctuation, %{language: :sql}, 41},
      {:whitespace, %{language: :sql}, " "},
      {:keyword_reserved, %{language: :sql}, "AS"},
      {:whitespace, %{language: :sql}, " "},
      {:name, %{language: :sql}, ~c"dates"},
      {:whitespace, %{language: :sql}, "\n "},
      {:comment_single, %{language: :sql}, ["--", 32, 99, 111, 109, 109, 101, 110, 116]},
      {:whitespace, %{language: :sql}, "\n "},
      {:punctuation, %{language: :sql}, 41},
      {:whitespace, %{language: :sql}, "\n  "},
      {:keyword_reserved, %{language: :sql}, "SELECT"},
      {:whitespace, %{language: :sql}, " "},
      {:name, %{language: :sql}, ~c"dates"},
      {:punctuation, %{language: :sql}, 46},
      {:keyword_reserved, %{language: :sql}, "date"},
      {:whitespace, %{language: :sql}, " "},
      {:keyword_reserved, %{language: :sql}, "AS"},
      {:whitespace, %{language: :sql}, " "},
      {:keyword_reserved, %{language: :sql}, "day"},
      {:punctuation, %{language: :sql}, 44},
      {:whitespace, %{language: :sql}, " "},
      {:keyword_reserved, %{language: :sql}, "count"},
      {:punctuation, %{language: :sql}, 40},
      {:name, %{language: :sql}, ~c"clicks"},
      {:punctuation, %{language: :sql}, 46},
      {:name, %{language: :sql}, ~c"id"},
      {:punctuation, %{language: :sql}, 41},
      {:whitespace, %{language: :sql}, " "},
      {:keyword_reserved, %{language: :sql}, "AS"},
      {:whitespace, %{language: :sql}, " "},
      {:keyword_reserved, %{language: :sql}, "count"},
      {:whitespace, %{language: :sql}, "\n    "},
      {:keyword_reserved, %{language: :sql}, "FROM"},
      {:whitespace, %{language: :sql}, " "},
      {:name, %{language: :sql}, ~c"computed_dates"},
      {:whitespace, %{language: :sql}, " "},
      {:keyword_reserved, %{language: :sql}, "AS"},
      {:whitespace, %{language: :sql}, " "},
      {:name, %{language: :sql}, ~c"dates"},
      {:whitespace, %{language: :sql}, "\n         "},
      {:keyword_reserved, %{language: :sql}, "LEFT"},
      {:whitespace, %{language: :sql}, " "},
      {:keyword_reserved, %{language: :sql}, "JOIN"},
      {:whitespace, %{language: :sql}, " "},
      {:name, %{language: :sql}, ~c"clicks"},
      {:whitespace, %{language: :sql}, " "},
      {:keyword_reserved, %{language: :sql}, "AS"},
      {:whitespace, %{language: :sql}, " "},
      {:name, %{language: :sql}, ~c"clicks"},
      {:whitespace, %{language: :sql}, " "},
      {:keyword_reserved, %{language: :sql}, "ON"},
      {:whitespace, %{language: :sql}, " "},
      {:keyword_reserved, %{language: :sql}, "date"},
      {:punctuation, %{language: :sql}, 40},
      {:name, %{language: :sql}, ~c"clicks"},
      {:punctuation, %{language: :sql}, 46},
      {:name, %{language: :sql}, ~c"inserted_at"},
      {:punctuation, %{language: :sql}, 41},
      {:whitespace, %{language: :sql}, " "},
      {:operator, %{language: :sql}, 61},
      {:whitespace, %{language: :sql}, " "},
      {:name, %{language: :sql}, ~c"dates"},
      {:punctuation, %{language: :sql}, 46},
      {:keyword_reserved, %{language: :sql}, "date"},
      {:whitespace, %{language: :sql}, "\n   "},
      {:keyword_reserved, %{language: :sql}, "WHERE"},
      {:whitespace, %{language: :sql}, " "},
      {:name, %{language: :sql}, ~c"clicks"},
      {:punctuation, %{language: :sql}, 46},
      {:name, %{language: :sql}, ~c"link_id"},
      {:whitespace, %{language: :sql}, " "},
      {:operator, %{language: :sql}, 61},
      {:whitespace, %{language: :sql}, " "},
      {:name, %{language: :sql}, "$2"},
      {:whitespace, %{language: :sql}, "\n"},
      {:keyword_reserved, %{language: :sql}, "GROUP"},
      {:whitespace, %{language: :sql}, " "},
      {:keyword_reserved, %{language: :sql}, "BY"},
      {:whitespace, %{language: :sql}, " "},
      {:name, %{language: :sql}, ~c"dates"},
      {:punctuation, %{language: :sql}, 46},
      {:keyword_reserved, %{language: :sql}, "date"},
      {:whitespace, %{language: :sql}, "\n"},
      {:keyword_reserved, %{language: :sql}, "ORDER"},
      {:whitespace, %{language: :sql}, " "},
      {:keyword_reserved, %{language: :sql}, "BY"},
      {:whitespace, %{language: :sql}, " "},
      {:name, %{language: :sql}, ~c"dates"},
      {:punctuation, %{language: :sql}, 46},
      {:keyword_reserved, %{language: :sql}, "date"},
      {:punctuation, %{language: :sql}, 59},
      {:whitespace, %{language: :sql}, "\n"}
    ]
  end
end
